Repository lotteon2/dailyon-frontend, pull requests merged in 2023-12, with the labels that each got.

#9 O2 f 434 frontend sns /feat/create post
  src/apis/ootd/FileService.ts
  src/apis/ootd/PostDto.ts
  src/apis/ootd/PostService.ts
  src/assets/css/ootd/ootd-post-create.css
  src/assets/css/ootd/ootd-product-search-modal.css
  src/assets/images/default-product-img.png
  src/components/ootd/OOTDFollowerTableComponent.vue
  src/components/ootd/OOTDFollowingTableComponent.vue
  src/components/ootd/OOTDProductSearchModalComponent.vue
  src/views/OOTDPostCreateView.vue
Labels: documentation, enhancement

#12 O2F-535 O2F-536 [FEAT] 댓글 및 답글 등록 CSS, HTML 구현 및 API 연동
  src/assets/css/ootd/ootd-post-comment.css
  src/components/ootd/OOTDPostCommentComponent.vue
Labels: documentation, enhancement

#13 O2F-542 O2F-543 O2F-544 [FEAT] 댓글 삭제 프론트엔드 구현
  src/apis/ootd/CommentService.ts
  src/components/ootd/OOTDPostCommentComponent.vue
Labels: documentation, enhancement

#16 O2F-518 O2F-519 O2F-520 [FEAT] 게시글 상세 조회 프론트엔드 구현
  src/apis/ootd/PostDto.ts
  src/apis/ootd/ProductSearchService.ts
  src/assets/css/ootd/ootd-detail.css
  src/assets/css/ootd/ootd-post-comment.css
  src/components/ootd/OOTDProductSearchModalComponent.vue
  src/views/OOTDDetailView.vue
  src/views/OOTDPostCreateView.vue
Labels: documentation, enhancement

#18 O2F-530 O2F-531 O2F-532 [FEAT] 게시글 삭제 구현
  src/apis/ootd/PostService.ts
  src/views/OOTDDetailView.vue
Labels: documentation, enhancement

#20 O2 f 560 frontend /refactor/sns
  src/App.vue
  src/apis/ootd/PostDto.ts
  src/assets/css/ootd/ootd-detail.css
  src/assets/css/ootd/ootd-post-card.css
  src/assets/css/ootd/ootd-post-comment.css
  src/assets/css/ootd/ootd.css
  src/assets/css/ootd/sort.css
  src/assets/css/pagination.css
  src/assets/footer.css
  src/assets/header.css
  src/assets/main.css
  src/components/HeaderComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/PaginationComponent.vue
  src/views/OOTDDetailView.vue
Labels: bug, documentation

#21 O2F-595 [REFACTOR] 게시글 좋아요 토글 로직 변경
  src/apis/ootd/PostLikeService.ts
  src/components/ootd/MemberOOTDPostComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/views/OOTDDetailView.vue
Labels: documentation

#22 O2F-595 O2F-752 [REFACTOR] 팔로우 관련 리팩터링
  src/apis/ootd/FollowService.ts
  src/assets/css/follow.css
  src/assets/css/mypage-navbar.css
  src/assets/mypage.css
  src/components/ootd/OOTDFollowComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/views/OOTDDetailView.vue
Labels: documentation, enhancement

#23 O2 f 560 frontend /refactor/sns
  src/components/ootd/MemberOOTDPostComponent.vue
  src/components/ootd/OOTDFollowComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/views/OOTDDetailView.vue
Labels: bug, documentation, enhancement

#24 O2F-595 [REFACTOR] 게시글 및 팔로우 토글 새로고침 및 브라우저 창 종료 버그 해결
  src/components/ootd/OOTDFollowComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/views/OOTDDetailView.vue
Labels: bug, documentation

#26 O2F-595 [REFACTOR] 마이페이지 반응형 페이지 제작
  src/apis/utils/index.ts
  src/assets/css/mypage-header.css
  src/assets/css/mypage-navbar.css
  src/assets/css/ootd/my-ootd-post.css
  src/assets/mypage.css
  src/components/MyPageHeaderComponent.vue
  src/components/ootd/MyOOTDPostComponent.vue
  src/components/ootd/OOTDPostLikeComponent.vue
Labels: documentation

#28 Fix/api url
  src/apis/ootd/CommentService.ts
  src/apis/ootd/FollowService.ts
  src/apis/ootd/MemberService.ts
  src/apis/ootd/PostDto.ts
  src/apis/ootd/PostLikeService.ts
  src/apis/ootd/PostService.ts
  src/apis/ootd/ProductSearchService.ts
  src/assets/css/ootd/ootd-detail.css
  src/views/OOTDDetailView.vue
Labels: bug, documentation

#29 O2F-594 [FEAT] 게시글 조회수 로직 구현
  src/apis/ootd/PostService.ts
  src/stores/post/PostStore.ts
  src/views/OOTDDetailView.vue
Labels: documentation, enhancement

#30 O2F-788 [FEAT] 이미지 리사이징 도입 및 프론트 적용
  src/assets/css/follow.css
  src/assets/images/loading.gif
  src/components/ootd/OOTDFollowerTableComponent.vue
  src/components/ootd/OOTDFollowingTableComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
Labels: documentation, enhancement

#58 O2 f 1027 sns frontend /feat/sns product search
  package-lock.json
  package.json
  src/App.vue
  src/apis/ootd/ProductSearchService.ts
  src/assets/css/ootd/ootd-post-create.css
  src/components/ootd/OOTDProductSearchModalComponent.vue
  src/views/OOTDPostCreateView.vue
Labels: documentation, enhancement

#61 O2F-1035 [FIX] 자기자신 팔로우 언팔로우 불가 수정
  src/components/ootd/OOTDProfileCardComponent.vue
  src/views/OOTDDetailView.vue
Labels: bug

#63 O2F-1035 [FIX] 페이지 새로고침 flush 이벤트 수정
  src/components/ootd/OOTDFollowComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/views/OOTDDetailView.vue
  src/views/OOTDView.vue
Labels: bug

#66 release
  src/apis/member/MemberDto.ts
  src/apis/member/member.ts
  src/apis/product/ProductDto.ts
  src/assets/css/member-info.css
  src/assets/css/mypage-header.css
  src/assets/header.css
  src/assets/product-detail.css
  src/components/HeaderCategoryComponent.vue
  src/components/MyPageHeaderComponent.vue
  src/components/member/MemberInfoComponent.vue
  src/components/ootd/OOTDFollowComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDPostCommentComponent.vue
  src/components/ootd/OOTDProductSearchModalComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/components/order/OrderDetailComponent.vue
  src/components/order/OrderSheetComponent.vue
  src/components/product/BreadCrumbComponent.vue
  src/views/OOTDDetailView.vue
  src/views/ProductListView.vue
Labels: release

#70 release
  src/apis/category/CategoryDto.ts
  src/apis/member/MemberDto.ts
  src/apis/member/member.ts
  src/assets/css/member-info.css
  src/assets/header.css
  src/components/HeaderCategoryComponent.vue
  src/components/HeaderComponent.vue
  src/components/MyPageHeaderComponent.vue
  src/components/member/AddressModal.vue
  src/components/member/MemberInfoComponent.vue
  src/components/member/PointHistoryComponent.vue
  src/stores/category/CategoryStore.ts
Labels: release

#73 Develop
  src/apis/ootd/PostDto.ts
  src/apis/ootd/PostService.ts
  src/assets/product-detail.css
  src/components/ootd/TOP4OOTDComponent.vue
  src/components/product/DescribeImageComponent.vue
  src/views/ProductDetailView.vue
  src/views/ProductListView.vue
Labels: release

#76 Develop
  src/apis/coupon/coupon.ts
  src/apis/order/orderDto.ts
  src/apis/review/review.ts
  src/apis/review/reviewDto.ts
  src/apis/s3/S3Client.ts
  src/assets/css/cart.css
  src/assets/css/order/order-detail.css
  src/assets/css/wish.css
  src/components/member/AddressModal.vue
  src/components/member/MemberInfoComponent.vue
  src/components/order/OrderComponent.vue
  src/components/order/OrderDetailComponent.vue
  src/components/order/OrderHistoryComponent.vue
  src/components/order/orderDetail/OrderDetailComponent.vue
  src/components/product/ReviewComponent.vue
  src/components/wishcart/CartComponent.vue
  src/components/wishcart/WhitePageComponent.vue
  src/components/wishcart/WishComponent.vue
  src/views/OOTDDetailView.vue
  src/views/OOTDProfileView.vue
Labels: release
