Repository lotteon2/dailyon-frontend, pull requests merged in 2024-01, with the labels that each got.

#84 release
  src/assets/css/member-info.css
  src/components/member/AddressModal.vue
  src/components/member/MemberInfoComponent.vue
  src/router/index.ts
  src/views/NotFoundView.vue
Labels: release

#91 [FIX] api 에러 처리 수정
  src/apis/ootd/CommentService.ts
  src/apis/ootd/FollowService.ts
  src/apis/ootd/MemberService.ts
  src/apis/ootd/PostLikeService.ts
  src/apis/ootd/PostService.ts
  src/apis/ootd/ProductSearchService.ts
  src/components/order/OrderPlaceComponent.vue
  src/router/index.ts
Labels: release

#104 release
  src/assets/css/ootd/ootd-detail.css
  src/assets/css/ootd/ootd-post-create.css
  src/assets/css/ootd/ootd-post-update.css
  src/components/MyPageHeaderComponent.vue
  src/components/ootd/OOTDPostCommentComponent.vue
  src/views/OOTDDetailView.vue
  src/views/OOTDPostCreateView.vue
  src/views/OOTDPostUpdateView.vue
  src/views/PaymentSuccessView.vue
Labels: release

#114 Develop
  src/apis/coupon/CouponItemDto.ts
  src/apis/coupon/coupon.ts
  src/apis/member/member.ts
  src/apis/utils/index.ts
  src/assets/css/coupon/product-detail-coupon-modal.css
  src/assets/css/member-info.css
  src/components/HeaderComponent.vue
  src/components/MyPageHeaderComponent.vue
  src/components/MyPageNavbarComponent.vue
  src/components/member/MemberInfoComponent.vue
  src/components/promotion/coupon/productdetail/ProductDetailCouponModal.vue
  src/views/LoginGetInfo.vue
  src/views/ProductDetailView.vue
Labels: release

#119 Feat/common design
  src/assets/css/mypage-header.css
  src/components/HeaderComponent.vue
  src/components/MyPageHeaderComponent.vue
  src/components/wishcart/CartComponent.vue
  src/components/wishcart/WishComponent.vue
  src/router/index.ts
  src/views/BestProductView.vue
  src/views/HomeView.vue
  src/views/NewProductView.vue
Labels: bug

#118 release
  src/apis/notification/notification.ts
  src/assets/css/mypage-header.css
  src/components/HeaderComponent.vue
  src/components/MyPageHeaderComponent.vue
  src/components/promotion/coupon/checkout/CheckoutCouponModal.vue
  src/components/promotion/coupon/productdetail/CouponItemComponent.vue
  src/components/promotion/coupon/productdetail/ProductDetailCouponModal.vue
  src/components/wishcart/CartComponent.vue
  src/components/wishcart/WishComponent.vue
  src/router/index.ts
  src/stores/notification/NotificationStore.ts
  src/views/BestProductView.vue
  src/views/HomeView.vue
  src/views/NewProductView.vue
  src/views/OrderView.vue
Labels: release

#122 [FIX] fix search logic
  src/views/ProductSearchView.vue
Labels: bug

#135 release
  package-lock.json
  package.json
  src/apis/notification/notification.ts
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/types/notification.ts
  src/views/OOTDDetailView.vue
  tsconfig.vitest.json
Labels: release

#138 release
  src/components/HeaderComponent.vue
  src/components/MyPageHeaderComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/stores/notification/NotificationStore.ts
  src/views/OOTDDetailView.vue
Labels: release

#157 [FIX] fix ootd image resize logic
  src/assets/css/ootd/ootd-post-card.css
  src/components/ootd/OOTDPostCardComponent.vue
  src/views/OOTDDetailView.vue
Labels: release

#165 release
  src/assets/product-detail.css
  src/components/HeaderCategoryComponent.vue
  src/components/ootd/TOP4OOTDComponent.vue
  src/components/product/ReviewComponent.vue
  src/views/ProductDetailView.vue
  src/views/ProductListView.vue
Labels: release

#166 [STYLE] remove unused navbar and down font weight in category bar
  src/components/HeaderCategoryComponent.vue
  src/components/MyPageNavbarComponent.vue
Labels: release

#167 release
  src/apis/auction/AuctionClient.ts
  src/apis/coupon/coupon.ts
  src/apis/delivery/delivery.ts
  src/apis/member/member.ts
  src/apis/ootd/CommentService.ts
  src/apis/ootd/FollowService.ts
  src/apis/ootd/MemberService.ts
  src/apis/ootd/PostLikeService.ts
  src/apis/ootd/PostService.ts
  src/apis/ootd/ProductSearchService.ts
  src/apis/order/order.ts
  src/apis/payment/payment.ts
  src/apis/product/ProductClient.ts
  src/apis/review/review.ts
  src/apis/utils/index.ts
  src/apis/wishcart/WishListClient.ts
  src/components/FooterComponent.vue
  src/components/MyPageHeaderComponent.vue
  src/components/auction/AuctionEntranceModal.vue
  src/components/gifts/GiftAddressModal.vue
  src/components/member/AddressModal.vue
  src/components/member/MemberInfoComponent.vue
  src/components/ootd/MemberOOTDPostComponent.vue
  src/components/ootd/MyOOTDPostComponent.vue
  src/components/ootd/OOTDFollowComponent.vue
  src/components/ootd/OOTDFollowerTableComponent.vue
  src/components/ootd/OOTDFollowingTableComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDPostCommentComponent.vue
  src/components/ootd/OOTDPostLikeComponent.vue
  src/components/ootd/OOTDProductSearchModalComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/components/order/OrderAddressModal.vue
  src/components/order/OrderComponent.vue
  src/components/order/OrderHistoryComponent.vue
  src/components/order/OrderPaymentComponent.vue
  src/components/order/OrderPlaceComponent.vue
  src/components/order/OrderSheetComponent.vue
  src/components/order/orderDetail/OrderDetailComponent.vue
  src/components/product/BreadCrumbComponent.vue
  src/components/promotion/coupon/productdetail/ProductDetailCouponModal.vue
  src/components/wishcart/CartComponent.vue
  src/components/wishcart/WishComponent.vue
  src/router/index.ts
  src/utils/Modal.ts
  src/utils/Toast.ts
  src/views/LoginGetInfo.vue
  src/views/OOTDDetailView.vue
  src/views/OOTDPostCreateView.vue
  src/views/OOTDPostUpdateView.vue
  src/views/OOTDView.vue
  src/views/OrderView.vue
  src/views/ProductDetailView.vue
  src/views/ProductListView.vue
Labels: release

#170 release
  src/App.vue
  src/apis/order/orderDto.ts
  src/apis/product/ProductDto.ts
  src/components/HeaderComponent.vue
  src/components/ootd/OOTDPostCardComponent.vue
  src/components/ootd/OOTDPostCommentComponent.vue
  src/components/ootd/OOTDProfileCardComponent.vue
  src/components/promotion/coupon/checkout/CheckoutCouponModal.vue
  src/components/wishcart/CartComponent.vue
  src/components/wishcart/WishComponent.vue
  src/router/index.ts
  src/stores/product/ProductStore.ts
  src/types/notification.ts
  src/utils/CommonMessage.ts
  src/utils/Toast.ts
  src/views/OOTDDetailView.vue
  src/views/OrderView.vue
  src/views/ProductDetailView.vue
  src/views/ProductSearchView.vue
Labels: release

#181 Develop
  src/apis/category/CategoryClient.ts
  src/apis/category/CategoryDto.ts
  src/apis/product/ProductClient.ts
  src/apis/wishcart/CartClient.ts
  src/apis/wishcart/WishListClient.ts
  src/apis/wishcart/WishListDto.ts
  src/assets/home.css
  src/components/HeaderCategoryComponent.vue
  src/components/product/BreadCrumbComponent.vue
  src/components/wishcart/CartComponent.vue
  src/components/wishcart/WishComponent.vue
  src/stores/category/CategoryStore.ts
  src/views/ProductListView.vue
Labels: release

#218 release
  src/apis/product/ProductDto.ts
  src/components/product/ProductListPriceDisplay.vue
  src/components/promotion/coupon/productdetail/ProductDetailCouponModal.vue
  src/views/ProductDetailView.vue
  src/views/ProductListView.vue
Labels: release

#226 [FIX] fix notification read when empty notification
  src/components/notification/NotificationComponent.vue
Labels: bug, release

#230 [FIX] fix product list css
  src/components/product/ProductListPriceDisplay.vue
  src/views/ProductDetailView.vue
  src/views/ProductListView.vue
Labels: release

#233 release
  src/assets/css/ootd/ootd-detail.css
  src/assets/css/ootd/ootd-post-comment.css
  src/assets/css/ootd/ootd-post-create.css
  src/assets/css/ootd/ootd-post-update.css
  src/components/ootd/OOTDPostCommentComponent.vue
Labels: release

#238 [STYLE] revise sorting order about ootd
  src/components/ootd/MemberOOTDPostComponent.vue
  src/components/ootd/MyOOTDPostComponent.vue
  src/components/ootd/OOTDPostLikeComponent.vue
  src/components/order/OrderHistoryComponent.vue
  src/views/OOTDView.vue
Labels: release
